### ISSUE TITLE
AzCopy not found

### ISSUE THREAD

**Issue by nicoride93** [PeterDaveHello/docker-azcopy#3]
Hello,

Im getting this error when lunching the https://githubmemory.com/repo/PeterDaveHello/docker-azcopy

Error: Failed to start container test, Error response: to create containerd task: failed to create container 43a24db01d614c8bf63ea99b2d1fd3de76ac54aeaddc3d334b188e986de9928a: guest RPC failure: failed to create container: failed to run runc create/exec call for container 43a24db01d614c8bf63ea99b2d1fd3de76ac54aeaddc3d334b188e986de9928a with container_linux.go:349: starting container process caused "exec: \"azcopy copy 'https://nrrdtest.file.core.wind --preserve-smb-info --preserve-smb-permissions --recursive\": stat azcopy copy 'https://nrrdtest.file.core.wind --preserve-smb-info --preserve-smb-permissions --recursive: no such file or directory": exit status 1: unknown

Is there anything Im doing wrong?

**Comment by PeterDaveHello** [comment]
@nicoride93 what's your environment and command?

**Comment by nicoride93** [comment]
Im following this github
https://github.com/Azure-Samples/azure-files-samples/tree/master/SyncBetweenTwoAzureFileSharesForDR
(did some modifications on the container group creation)

This is the PS script 
$container = New-AzContainerInstanceObject -Name azcopyjob -Image "peterdavehello/azcopy" -RequestCpu 2 -RequestMemoryInGb 4 -Command $command
New-AzContainerGroup -ResourceGroupName $sourceStorageAccountRG -Name azcopyjob-cg -Location WestUs2 -Container $container -OsType Linux -RestartPolicy never

And this is the command
azcopy copy 'https://wvdnrrd.file.core.windows.net/profiles?sharesnapshot=2021-09-21T15%3A59%3A03.0000000Z&sv=2019-07-07&sr=s&sig=Gmc8hnrzEBa3aOFQ5kEbdidSZ7QxIiLhITAaVombZ3Y%3D&se=2021-09-22T16%3A01%3A34Z&sp=rl' 'https://nrrdpremium.file.core.win
dows.net/profiles?sv=2019-07-07&sr=s&sig=9A5ZfH8EczJhEj9QHRC0m24gyIIfIdVDPLZXRRBQjbg%3D&se=2021-09-22T17%3A17%3A57Z&sp=rwl' --preserve-smb-info --preserve-smb-permissions --recursive

**Comment by PeterDaveHello** [comment]
@nicoride93 Are you taking an Azure training that have an instructor can help you take a look? I'd suggest you to make sure that your commend works fine with azcopy but without Docker, and then test the command with a container.

**Comment by nicoride93** [comment]
It did worked on my machine but is not working on docker
azcopy copy 'https://wvdnrrd.file.core.windows.net/profiles?sharesnapshot=2021-09-21T19%3A30%3A06.0000000Z&sv=2019-07-07&sr=s&sig=9%2FcWVoyFjS27cO8tNgXqv%2FzD3atAof9Qt5LLu9SbNGE%3D&se=2021-09-22T19%3A30%3A03Z&sp=rl' 'https://nrrdpremium.file.core.windows.net/profiles?sv=2019-07-07&sr=s&sig=SsMVSdtUg1BXbzo1mgedTYxjV9r0%2BiidkqmZFb544H4%3D&se=2021-09-22T19%3A30%3A08Z&sp=rwl' --preserve-smb-info=true --preserve-smb-permissions=true --recursive

That one is the command

**Comment by nicoride93** [comment]
Error: Failed to start container test, Error response: to create containerd task: failed to create container 717aec9f046e25c86f1a12ee9fbfe1653d21188888ee83219d8e2a74be7c96f2: guest RPC failure: failed to create container: failed to run runc create/exec call for container 717aec9f046e25c86f1a12ee9fbfe1653d21188888ee83219d8e2a74be7c96f2 with container_linux.go:349: starting container process caused "exec: \"azcopy --version\": executable file not found in $PATH": exit status 1: unknown |  

I tried to run version and it also failed

**Comment by PeterDaveHello** [comment]
@nicoride93 Can you try to simply run the container without the PowerShell script? Looks weird here.

**Comment by nicoride93** [comment]
@PeterDaveHello without the script is booting up correctly

**Comment by PeterDaveHello** [comment]
@nicoride93 so I think the problem is most likely related to the script, not the image?

**Comment by nicoride93** [comment]
I dont know. I cannot get docker to work on my machine. The wierd part is that even the simplest command is not working (azcopy --version)

**Comment by PeterDaveHello** [comment]
@nicoride93 any other images tested with the similar usage but got no problem at all?

**Comment by nicoride93** [comment]
Now everything is working. It was an issue with the powershell version that I was using. 
thanks for the support!

**Comment by PeterDaveHello** [comment]
@nicoride93 Nice, glad you found the problem!
